disableKinds:
- sitemap
- taxonomy
- term
outputs:
  home:
  - html
caches:
  getresource:
    maxAge: 0
publishDir: generated_content
params:
  format: yaml_raw
  collections:
    - name: profiles
      content:
      min: 0
      max: 2
    - name: posts
      content:
        min: 3
        max: 10
    - name: events
    - name: products
      iterations: 3