baseURL: https://wwww.tnd-data-set.com
disableKinds:
- sitemap
- taxonomy
- term
outputs:
  home:
  - html
caches:
  getresource:
    maxAge: 0
publishDir: generated_content
params:
  tnd_data_gen:
    format: yaml
    collections:
      - name: profiles
        limit: 30
        # transformer: retro_703
        content:
          min: 1
          max: 1
          blocks: 
          - paragraph
      - name: posts
        limit: 140
        content:
          min: 1
          max: 1
        blocks:
          min: 1
          max: 5