disableKinds:
- sitemap
- taxonomy
- term
outputs:
  home:
  - html
caches:
  getresource:
    maxAge: 0
publishDir: generated_content
params:
  format: yaml
  collections:
    - name: profiles
      limit: 200
      transformer: retro_703
      content:
        min: 1
        max: 1
        blocks: 
        - paragraph
    - name: posts
      limit: 20
      blocks:
        min: 1
        max: 5
      content:
        min: 3
        max: 10
    - name: events
    - name: products
      limit: 10